/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSetting: typeof import('./components/AboutSetting.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    CalendarTodo: typeof import('./components/CalendarTodo.vue')['default']
    DateTimePicker: typeof import('./components/ui/DateTimePicker.vue')['default']
    Dropdown: typeof import('./components/ui/Dropdown.vue')['default']
    ImageViewer: typeof import('./components/ImageViewer.vue')['default']
    Input: typeof import('./components/ui/Input.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    NoteCard: typeof import('./components/NoteCard.vue')['default']
    NoteEditor: typeof import('./components/NoteEditor.vue')['default']
    NoteHeatmap: typeof import('./components/NoteHeatmap.vue')['default']
    NoteSidebar: typeof import('./components/NoteSidebar.vue')['default']
    PreferencesSetting: typeof import('./components/PreferencesSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/ui/Select.vue')['default']
    SelectionMenu: typeof import('./components/SelectionMenu.vue')['default']
    Statistics: typeof import('./components/Statistics.vue')['default']
    SyncSetting: typeof import('./components/SyncSetting.vue')['default']
    TagTreeNode: typeof import('./components/TagTreeNode.vue')['default']
    ThemeSetting: typeof import('./components/ThemeSetting.vue')['default']
    TodayTodoList: typeof import('./components/TodayTodoList.vue')['default']
    TodoDialog: typeof import('./components/TodoDialog.vue')['default']
    Toggle: typeof import('./components/ui/Toggle.vue')['default']
    WindowControls: typeof import('./components/ui/WindowControls.vue')['default']
  }
}
