/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ModelSetting: typeof import('./components/ModelSetting.vue')['default']
    NoteCard: typeof import('./components/NoteCard.vue')['default']
    NoteEditor: typeof import('./components/NoteEditor.vue')['default']
    PreferencesSetting: typeof import('./components/PreferencesSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionMenu: typeof import('./components/SelectionMenu.vue')['default']
    TerminalTab: typeof import('./components/TerminalTab.vue')['default']
    ThemeSetting: typeof import('./components/ThemeSetting.vue')['default']
    XTerm: typeof import('./components/XTerm.vue')['default']
  }
}
